[package]
name = "actix-web-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4", features = [] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.94"
log = "0.4"
env_logger = "0.10.0"